version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nodemailer
    versions:
    - 6.4.18
    - 6.5.0
    - 6.6.0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
